In [ ]:
NUMPY 

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [8]:
#when we store sliced value from numpy arrays they acts as views and values can be mutable from view and will reflect in original array
arr = np.array([1, 2, 3, 4, 5])
b = arr[1:]
b[0] = 20

arr

array([ 1, 20,  3,  4,  5])

In [10]:
#finding dimensions of numpy array
arr = np.array([1, 2, 3, 4])
print("dimensions of the numpy array: ", arr.ndim)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("dimensions of the numpy array: ", arr.ndim)

dimensions of the numpy array:  1
dimensions of the numpy array:  2


In [11]:
#finding shape of the numpy array
arr = np.array([1, 2, 3])
print("shape of the numpy array: ", arr.shape)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape of the numpy array: ", arr.shape)

shape of the numpy array:  (3,)
shape of the numpy array:  (2, 3)


In [ ]:
#finding size of the numpy array (product of its dimensions)
arr = np.array([1, 2, 3])
print("size of the numpy array: ", arr.size)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("size of the numpy array: ", arr.size)

size of the numpy array:  3
size of the numpy array:  6


In [17]:
#numpy arrays are homogenious, means all elements are in same type
arr = np.array([1, 2, 3])
print("data type of the numpy array will be: ", arr.dtype)

arr = np.array([["a", "b", "c"], ["de", "fgh", "i"]])
print("data type of the numpy array will be: ", arr.dtype) #<U3 refers to unsigned 24 bits per element

arr = np.array([1.2, 2., 3])
print("data type of the numpy array will be: ", arr.dtype)

data type of the numpy array will be:  int32
data type of the numpy array will be:  <U3
data type of the numpy array will be:  float64


In [2]:
#creating numpy arrays that are filled with 0's 
zeroes = np.zeros(2)
print("arr: ", zeroes)

zeroes = np.zeros((2, 2))
print("arr: ", zeroes)

arr:  [0. 0.]
arr:  [[0. 0.]
 [0. 0.]]


In [3]:
#similarly we can also do with ones 
ones = np.ones(2)
print("arr: ", ones)

ones = np.ones((2, 3))
print("arr: ", ones)

arr:  [1. 1.]
arr:  [[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#to create range of elements as numpy array
arr = np.arange(4)
print("arr: ", arr)

arr = np.arange(0, 5)
print("arr: ", arr)

arr = np.arange(0, 10, 2)
print("arr: ", arr)

arr:  [0 1 2 3]
arr:  [0 1 2 3 4]
arr:  [0 2 4 6 8]


In [10]:
# we can do linspace in numpy to create array with elements the distributed in equal intervals in linear fashion
arr = np.linspace(0, 10, num=5)
print("arr: ", arr)

arr:  [ 0.   2.5  5.   7.5 10. ]


In [ ]:
#while creating numpy array default data type is np.float64
arr = np.ones(2, dtype=np.int64)
arr

array([1., 1.])

In [ ]:
#conatenate multiple numpy arrays of same dimensions and columns

arr1 = np.array([[1, 2]])

arr2 = np.array([[4, 5], [6, 7]])

arr = np.concatenate((arr1, arr2))

print("arr: ", arr)

arr:  [[1 2]
 [4 5]
 [6 7]]


In [6]:
#reshaping array in numpy
arr = np.arange(1,10)
arr = arr.reshape((3,3))
print("arr: ", arr)

arr = np.arange(1,10)
arr = np.reshape(arr, (3, 3), order="C")
print("arr: ", arr)

arr:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
'''
we can order the numpy arrays either as C or F

C -> it orders the elemenets in row wise in memory while storing

F(Fortran) -> it orders the elements in column wise
'''

In [ ]:
#we can split the numpy array column wise using hsplit
arr = np.array([1,2,3,4])
arr = np.hsplit(arr, (1,2)) # it split columns at before index 1 and index 2 
print("arr: ", arr)

arr = np.array([1,2,3,4,5])
arr = np.hsplit(arr, 5) # it will split array in 5 equal parts
print("arr: ",arr)


arr:  [array([1]), array([2]), array([3, 4])]
arr:  [array([1]), array([2]), array([3]), array([4]), array([5])]


In [12]:
#sum of elements in array, row wise, column wise
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("full sum: ", arr.sum())

#row sum
print("row sum: ", arr.sum(axis=1))

#column sum
print("column sum: ", arr.sum(axis=0))

full sum:  36
row sum:  [10 26]
column sum:  [ 6  8 10 12]


In [13]:
#transpose numpy array
arr = np.array([[1,2], [3, 4]])
print("array transpose: ", arr.transpose())

array transpose:  [[1 3]
 [2 4]]


In [16]:
#reverse the array
arr = np.array([[1,2], [3, 4]])
print("array reverse: ", np.flip(arr))

#reverse only rows
print("reversing row of array: ", np.flip(arr, axis=1))

#reverse only columns
print("reversing columns of array: ", np.flip(arr, axis=0))

array reverse:  [[4 3]
 [2 1]]
reversing row of array:  [[2 1]
 [4 3]]
reversing columns of array:  [[3 4]
 [1 2]]
