In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM

c:\Users\venuv\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
model_name = "distilgpt2"
tokernizer = AutoTokenizer.from_pretrained(
    model_name
)

model = AutoModelForCausalLM.from_pretrained(
    model_name
)

Loading weights: 100%|██████████| 76/76 [00:00<00:00, 5842.61it/s]


In [11]:
text = "Artificial Intelligence is"

tokens = tokernizer(
    text,
    return_tensors="pt"
)

print(tokens)

{'input_ids': tensor([[8001, 9542, 9345,  318]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [12]:
output = model.generate(
    **tokens,
    max_new_tokens=50
)

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [14]:
output

tensor([[ 8001,  9542,  9345,   318,   257,   649,  3037,   326,   318,   852,
          4166,   416,   262,  2059,   286,  3442,   379, 14727,    13,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198]])

In [13]:
print(tokernizer.decode(
    output[0],
    skip_special_tokens=True
))

Artificial Intelligence is a new technology that is being developed by the University of California at Berkeley.





































In [1]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "distilgpt2"
)

text = "Artificial Intelligence is amazing"

tokens = tokenizer.tokenize(text)

print(tokens)

ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

c:\Users\venuv\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


['Art', 'ificial', 'ĠIntelligence', 'Ġis', 'Ġamazing']
[8001, 9542, 9345, 318, 4998]


In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embedding = model.encode(
    "Artificial Intelligence is amazing",
    device="cpu"
)



Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6866.40it/s]


(384,)


In [4]:
print(embedding)

[-3.39681618e-02 -7.70122632e-02  6.37992993e-02 -4.28885110e-02
 -1.64864976e-02 -4.96060774e-02  1.75460000e-02  2.40138359e-02
  2.33090464e-02  5.26953489e-02 -2.33761556e-02  7.11734742e-02
  4.91071083e-02  3.26733626e-02 -8.62148926e-02 -1.00289695e-02
 -1.14877475e-02 -4.01038378e-02 -1.04304492e-01 -1.48092046e-01
 -1.61669776e-03  2.52723917e-02  3.57925743e-02 -5.37322797e-02
 -4.41776542e-03  6.55838847e-02  8.96786246e-03 -4.40217033e-02
  4.84723924e-03 -8.18367526e-02  4.68105124e-03  3.25825810e-02
  5.56443147e-02 -7.34381704e-03 -9.12890956e-02  7.18829185e-02
 -1.18353870e-02 -1.72401667e-02  5.02062365e-02 -3.15542594e-02
 -4.60796505e-02 -2.46168561e-02  5.20188622e-02 -2.85019111e-02
  6.92973286e-02  1.19127639e-01 -5.69971651e-02 -3.09821144e-02
  5.86087108e-02 -2.60721706e-03 -1.62945628e-01 -4.54234779e-02
  1.32279433e-02  1.63333919e-02 -3.49327363e-02  1.51828565e-02
 -3.53356730e-03 -2.37839017e-02 -2.94565223e-02 -5.38282841e-02
 -1.62676629e-02 -9.83770

In [9]:
from sentence_transformers import SentenceTransformer
from torch.nn.functional import cosine_similarity
import torch

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

s1 = model.encode(
    "I love machine learning",
    device="cpu"
)

s2 = model.encode(
    "I enjoy artificial intelligence",
    device="cpu"
)

s3 = model.encode(
    "The weather is sunny",
    device="cpu"
)

s1 = torch.tensor(s1)
s2 = torch.tensor(s2)
s3 = torch.tensor(s3)

print(
    cosine_similarity(
        s1.unsqueeze(0),
        s2.unsqueeze(0)
    )
)

print(
    cosine_similarity(
        s1.unsqueeze(0),
        s3.unsqueeze(0)
    )
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9633.91it/s]


tensor([0.6720])
tensor([0.0169])


In [10]:
print(s1.shape)
print(s2.shape)
print(s3.shape)

torch.Size([384])
torch.Size([384])
torch.Size([384])
